TRAIN:
  FROM: 合肥南
  TO: 余姚北
  FULLY_MATCH_FROM: false # 完全匹配出发站名
  FULLY_MATCH_TO: true # 完全匹配到达站名
  DATE: YYYY-mm-dd
  TRAIN_TYPE: G
  MIN_START_HOUR: 12
  MAX_START_HOUR: 15
  TIME: 13:00 # 期望的发车时间，在满足下面MODE的情况下优先考虑更接近该时间的车次
  MODE: both # 选择both、earlier、later之一，若为earlier，筛选不晚于期望时间的车；若为later，筛选不早于期望时间的车；若为both，则全选
PASSENGERS:
  - NAME: 张三
    TICKET_TYPE: 成人票
    SEAT_TYPE: 二等座
    SEAT: D
  - NAME: 李四
    TICKET_TYPE: 成人票
    SEAT_TYPE: 二等座
    SEAT: F